config/routes.rb
Rails.application.routes.draw do
  get 'invoice', to: 'invoice#index', as: 'invoice_index'
  get 'checkout', to: 'checkout#show', as: 'show_checkout'
  get 'cart', to: 'cart#show', as: 'show_cart'
  get 'contact', to: 'contact#index', as: 'contact'
  get 'about', to: 'about#index', as: 'about'
  get 'product/:id', to: 'product#show', as: 'show_product'

  root to: 'home#index'

  resources :home do
    member do
      post :add_product_to_cart
    end
  end

  resources :cart do
    member do
      post :delete_product_from_cart
    end

    collection do
      post :update_product_quantity
    end
  end

  resources :invoice do
    collection do
      post :index
      post :pay
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :province
  belongs_to :customer

  validates :type, :street, :city, :country,
            :postal_code, :customer_id,
            :province_id, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :customer

  validates :type, :name, :number, :verification_number, :due_date, :customer_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :nullify

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :products
  belongs_to :customers

  validates :content, :customer_id, :product_id, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :product_comments, dependent: :destroy

  validates :name, :email, :password, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  belongs_to :customer

  validates :status, :customer_id, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :price, :quantity, :product_id, :order_id, presence: true
  validates :price, :quantity, numericality: { greater_than: 0 }
end

app/models/page.rb
class Page < ApplicationRecord
  validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_comments, dependent: :destroy
  has_many :order_items, dependent: :nullify
  has_many :orders, through: :order_items
  belongs_to :category

  validates :name, :price, :stock_quantity, presence: true
  validates :price, :stock_quantity, numericality: { greater_than_or_equal_to: 0 }

  max_paginates_per 8

  mount_uploader :image, ProductUploader

  def self.search(search, category)
    query = "(name ILIKE '%#{search}%' OR description ILIKE '%#{search}%')"
    query += " AND category_id = #{category}" if category > 0
    where(query)
  end
end

app/models/product_comment.rb
class ProductComment < ApplicationRecord
  belongs_to :product
  belongs_to :customer

  validates :content, :customer_id, :product_id, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :addresses, dependent: :nullify

  validates :name, presence: true
  validates :code, length: { is: 2 }
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :initialize_session

  def show
    product_ids = []
    session[:shopping_cart].each { |e| product_ids << e['id'].to_i }
    @products = Product.find(product_ids)
    @shopping_cart = session[:shopping_cart]
  end

  def delete_product_from_cart
    id = params[:id].to_i
    product = session[:shopping_cart].find { |prod| prod['id'] == id }
    session[:shopping_cart].delete(product)
    flash[:notice] = 'Succesfully deleted product from cart.'
    redirect_back(fallback_location: show_cart_path)
  end

  def update_product_quantity
    item = session[:shopping_cart].find { |e| e['id'] == params[:id].to_i }
    item['quantity'] = params[:quantity]
    flash[:notice] = 'Updated product quantity.'
    redirect_back(fallback_location: show_cart_path)
  end

  def initialize_session
    session[:shopping_cart] ||= []
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/cart/show.html.slim
h1 Shopping Cart

/ = session[:shopping_cart].inspect

table id="cart" class="table table-hover table-condensed"
  thead
    tr
      th style="width:50%" Product
      th style="width:10%" Price
      th style="width:8%" Quantity
      / th style="width:22%" class="text-center" Subtotal
      th style="width:10%"
  tbody
    - @products.each do |product|
      tr
        td data-th="Product"
          div class="row"
            / div class="col-sm-2 hidden-xs"
            /   = link_to image_tag(product.image, class: 'img-responsive'), show_product_path(product.id)
            div class="col-sm-10"
              h6 = link_to "#{product.name}", show_product_path(product.id), class: 'nomargin'
        td data-th="Price"
          = "#{number_to_currency(product.price)}"
        td data-th="Quantity"
          = form_tag update_product_quantity_cart_index_path, method: 'post', :class => "form-inline my-2 my-lg-0" do
            = number_field_tag('quantity',
                  @shopping_cart.find { |e| e['id'] == product.id }['quantity'].to_i,
                  step: 1, min: 0,
                  max: product.stock_quantity,
                  class: 'form-control text-center')
            = hidden_field_tag 'id', product.id
            = submit_tag 'Update', class: "btn btn btn-primary my-2 my-sm-0"
        / td data-th="Subtotal" class="text-center" $1.99
        td class="actions" data-th=""
          = link_to '🗑️'.html_safe, delete_product_from_cart_cart_path(product.id), class: 'btn btn-outline-secondary btn-sm', role: 'button', method: :post
  tfoot
    tr
      td
        = link_to '< Continue Shopping', root_path, class: 'btn btn-warning'
      td class="hidden-xs"
      td class="hidden-xs text-center font-weight-bold"
      td
        = link_to 'Checkout >', show_checkout_path, class: 'btn btn-success btn-block'