config/routes.rb
Rails.application.routes.draw do
  get 'invoice', to: 'invoice#index', as: 'invoice_index'
  get 'checkout', to: 'checkout#show', as: 'show_checkout'
  get 'cart', to: 'cart#show', as: 'show_cart'
  get 'contact', to: 'contact#index', as: 'contact'
  get 'about', to: 'about#index', as: 'about'
  get 'product/:id', to: 'product#show', as: 'show_product'

  root to: 'home#index'

  resources :home do
    member do
      post :add_product_to_cart
    end
  end

  resources :cart do
    member do
      post :delete_product_from_cart
    end

    collection do
      post :update_product_quantity
    end
  end

  resources :invoice do
    collection do
      post :index
      post :pay
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :province
  belongs_to :customer

  validates :type, :street, :city, :country,
            :postal_code, :customer_id,
            :province_id, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :customer

  validates :type, :name, :number, :verification_number, :due_date, :customer_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :nullify

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :products
  belongs_to :customers

  validates :content, :customer_id, :product_id, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :product_comments, dependent: :destroy

  validates :name, :email, :password, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  belongs_to :customer

  validates :status, :customer_id, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :price, :quantity, :product_id, :order_id, presence: true
  validates :price, :quantity, numericality: { greater_than: 0 }
end

app/models/page.rb
class Page < ApplicationRecord
  validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_comments, dependent: :destroy
  has_many :order_items, dependent: :nullify
  has_many :orders, through: :order_items
  belongs_to :category

  validates :name, :price, :stock_quantity, presence: true
  validates :price, :stock_quantity, numericality: { greater_than_or_equal_to: 0 }

  max_paginates_per 8

  mount_uploader :image, ProductUploader

  def self.search(search, category)
    query = "(name ILIKE '%#{search}%' OR description ILIKE '%#{search}%')"
    query += " AND category_id = #{category}" if category > 0
    where(query)
  end
end

app/models/product_comment.rb
class ProductComment < ApplicationRecord
  belongs_to :product
  belongs_to :customer

  validates :content, :customer_id, :product_id, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :addresses, dependent: :nullify

  validates :name, presence: true
  validates :code, length: { is: 2 }
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/common/_header.html.slim
nav class="navbar navbar-expand-md navbar-light bg-faded"
  button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation"
    span class="navbar-toggler-icon"
  span class="navbar-brand" Vintage Games
  div class="collapse navbar-collapse" id="navbarTogglerDemo01"
    ul class="navbar-nav mr-auto"
      li class="nav-item" = link_to 'Home', root_path, class: 'nav-link'
      li class="nav-item" = link_to 'About', about_path, class: 'nav-link'
      li class="nav-item" = link_to 'Contact', contact_path, class: 'nav-link'
      li class="nav-item" = link_to '&#x1F6D2;'.html_safe, show_cart_path, class: 'nav-link'
    = form_tag root_path, method: 'get', :class => "form-inline my-2 my-lg-0" do
      = text_field_tag :search, params[:search], placeholder: 'Search products', class: "form-control mr-sm-2"
      = collection_select(nil, :category, Category.all.to_a.unshift(Category.new(id: 0, name: 'All Categories')), :id, :name, {selected: 0}, {class: 'form-control mr-sm-2'})
      = submit_tag 'Search', class: "btn btn-outline-success my-2 my-sm-0"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render partial: 'common/header' %>

      <% if flash[:notice] %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:notice] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>